spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alliance?characterEncoding=utf-8&&userSSL=false
    username: root
    password: hxz123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  file:
#    name: spring-blog.log
mybatis:
  mapper-locations: [classpath:mapper/**Mapper.xml, classpath:generator/**Mapper.xml]
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true