server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alliance?characterEncoding=utf-8&&userSSL=false
    username: root
    password: "025026"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**   # 允许访问 static 映射
  servlet:
    multipart:
      max-file-size: 1000MB      # 设置为你想的上传文件最大限制
      max-request-size: 1000MB   # 设置为你想的上传文件最大限制

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  mapper-locations: [classpath:mapper/**Mapper.xml, classpath:generator/**Mapper.xml]
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false  # 关闭驼峰

upload:
  image-path: E:/uploads/images        # 设置为你的图片上传路径
  video-path: E:/uploads/videos/       # 设置为你的视频上传路径
  static-path: /static/                # 设置为你的静态资源访问路径
